baseURL = "https://theologic.us/"
languageCode = "en-us"
title = "Theologicus"
description = """
No pen, no words, no image can express to you the loveliness of my only, only Lord Jesus. – Samuel Rutherford"""
theme = "cupper-hugo-theme"
googleAnalytics = "G-V3GC3P3REE"
footnoteReturnLinkContents = "↩"

[params]
description = """
No pen, no words, no image can express to you the loveliness of my only, only Lord Jesus. 
– Samuel Rutherford"""
  
homeMetaContent = "Collection of theological and doctrinal writings from Joseph Louthan"
  
footer = 'Copyright &#xA9; [Joseph Louthan](/about/). Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/).'

dateFormat = "02 Jan 2006 15:04"
  
codePenUser = "joe"
  
katex = true
  
disqusShortname = "joelouthan"
  
google-fonts = [
    ["Cinzel", "100, 200, 300, 400, 500, 600, 700, 800, 900"]
  ]

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Recent"
    url = "/posts/"
    weight = 2
  [[menu.nav]]  
    name = "WORKS IN PROGRESS"
    weight = 9
  [[menu.nav]]
    name = """
      Bible Study: Romans"""
    url = "/tags/bible-study-romans/"
    weight = 10
  [[menu.nav]]
    name = """
    Commentary: Romans"""
    url = "/tags/commentary-romans/"
    weight = 11
  [[menu.nav]]
    name = """
      Now Sings My Soul:
      Psalmic Prayers"""
    url = "/tags/now-sings-my-soul-psalms/"
    weight = 12
  [[menu.nav]]
    name = """
      Reflections on the Pastoral Epistles"""
    url = "/tags/philosophy-of-ministry/"
    weight = 13
  [[menu.nav]]
    name = """
      Family Devotions: Luke"""
    url = "/tags/family-devotions-luke/"
    weight = 14
  [[menu.nav]]
    name = "MANUSCRIPTS"
    weight = 20
  [[menu.nav]]
    name = """
      Here is Love:
      Exposition on Romans 8"""
    url = "/tags/here-is-love/"
    weight = 21
  [[menu.nav]]
    name = """
      Family Devotions: Mark"""
    url = "/tags/family-devotions-mark/"
    weight = 22
  [[menu.nav]]
    name = """
      Prayers from The Lord's Prayer"""
    url = "/tags/the-lords-prayer/"
    weight = 23
  [[menu.nav]]
    name = """
      Ordo Salutis: 
      Devotions on Salvation"""
    url = "/tags/ordo-salutis/"
    weight = 24
  [[menu.nav]]
    name = "REFERENCES"
    weight = 30
  [[menu.nav]]
    name = """
      Scripture Prooftext on Thanksgiving"""
    url = "/tags/thanksgiving/"
    weight = 31
  [[menu.nav]]
    name = "AROUND THE WEB"
    weight = 90
  [[menu.nav]]
    name = """
      A Few Points"""
    url = "/tags/a-few-points-for-friday/"
    weight = 91
  [[menu.nav]]
    name = """
      Sundry Items"""
    url = "/tags/sundry-saturday/"
    weight = 92
  [[menu.nav]]
    name = "TAGS"
    url = "/tags/"
    weight = 10001
  [[menu.nav]]
    name = "CATEGORIES"
    url = "/categories/"
    weight = 10002
  [[menu.nav]]
    name = "Contact"
    url = "/about/"
    weight = 10010

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]