baseURL = "https://theologic.us/"
languageCode = "en-us"
title = "Theologicus"
description = "No pen, no words, no image can express to you the loveliness of my only, only Lord Jesus. - Samuel Rutherford"
theme = "cupper-theo"

[params]
  description = "No pen, no words, no image can express to you the loveliness of my only, only Lord Jesus. - Samuel Rutherford"
  
  homeMetaContent = "No pen, no words, no image can express to you the loveliness of my only, only Lord Jesus. - Samuel Rutherford"
  
  footer = 'Copyright &#xA9; [Joseph Louthan](/about/). Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/).'

  dateFormat = "02 Jan 2006 15:04"
  
  codePenUser = "joe"
  
  katex = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Recent"
    url = "/posts/"
    weight = 2
  [[menu.nav]]
    name = "Memoir: A Life of Compromise"
    url = "/tags/a-life-of-compromise/"
    weight = 3
  [[menu.nav]]
    name = "Monday :: Commentary: Romans"
	url = "/tags/commentary-romans/"
    weight = 11
  [[menu.nav]]
    name = "Tuesday :: Now Sings My Soul: Prayers based on the Psalms"
    url = "/tags/now-sings-my-soul-psalms/"
    weight = 12
  [[menu.nav]]
    name = "Wednesday :: Thinking Through Ministry: Journaling through Pastoral Epistles"
    url = "/tags/philosophy-of-ministry/"
    weight = 13
  [[menu.nav]]
    name = "Thursday :: Family Devotions: Luke"
    url = "/tags/family-devotions-luke/"
    weight = 14
  [[menu.nav]]
    name = "Friday :: A Few Points"
    url = "/tags/a-few-points-on-friday/"
    weight = 15
  [[menu.nav]]
    name = "Saturday :: Sundry Items"
    url = "/tags/sundry-saturdays/"
    weight = 16
  [[menu.nav]]
    name = "MANUSCRIPT :: Here is Love: Exposition in Romans 8"
    url = "/tags/here-is-love/"
    weight = 20
  [[menu.nav]]
    name = "MANUSCRIPT :: Family Devotions: Mark"
    url = "/tags/family-devotions-mark/"
    weight = 21
  [[menu.nav]]
    name = "MANUSCRIPT :: The Lord's Prayer"
    url = "/tags/the-lords-prayer/"
    weight = 22
  [[menu.nav]]
    name = "MANUSCRIPT :: Ordo Salutis: Devotions on Salvation"
    url = "/tags/ordo-salutis/"
    weight = 23
  [[menu.nav]]
    name = "REFERENCE :: Thanksgiving: Scriptural Reference on Thanks"
    url = "/tags/thanksgiving/"
    weight = 24
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 100
  [[menu.nav]]
    name = "Categories"
    url = "/categories/"
    weight = 101
  [[menu.nav]]
    name = "Contact"
    url = "/about/"
    weight = 1000

[markup.goldmark.renderer]
unsafe= true
