baseURL: "https://theologic.us"
title: Theologicus
paginate: 1000
theme: PaperMod

rssLimit: 100
copyright: "2022 Joseph Louthan All Rights Reserved"
languageCode: "en-us"

author:
    name: "Joseph Louthan"
    email: "joe@theologic.us"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: G-V3GC3P3REE

minify:
    disableXML: true
    minifyOutput: true

params:
    ShowPostNavLinks: true

    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Theologicus
    description: "Trying to waste my time with God."
    author: Joseph Louthan
    # images: ["/content/images/"]

    defaultTheme: auto # dark, light
    disableThemeToggle: false
    ShowReadingTime: true
    ShowShareButtons: true
    disableSpecial1stPost: false
    comments: false
    hidemeta: false
    showtoc: true
    tocopen: true

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "apple-touch-icon.png"
        safari_pinned_tab: "safari-pinned-tab.svg"

    label:
        text: "Home"
        icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Theologicus
        imageUrl: "images/1-smile-no-braces-portrait-bright-noback-x2-small.png"
        imageWidth: 100
        imageHeight: 100
        imageTitle: "Joseph Louthan"
        buttons:
            - name: What Is It?
              url: /about/
            - name: What Is It Not?
              url: /not-about/
            - name: Ministry Resume
              url: /resume/
            - name: Updates
              url: updates
            - name: Recent Posts
              url: posts
            - name: Sermons
              url: /categories/sermons/
            - name: "1689"
              url: /series/1689-baptist-confession-of-faith/
            - name: "Home Devotions: Mark"
              url: /series/home-devotions-mark/
            - name: "Home Devotions: Matthew"
              url: /series/home-devotions-matthew/
            - name: "Study: Romans"
              url: /series/study-romans/
            - name: "Study: Genesis"
              url: /series/study-genesis/
            - name: "Gospel NT: Pastoral Epistles"
              url: /series/gospel-nt-pastorals/
            - name: "Kid Devotions: Luke"
              url: /series/kid-devotions-luke/
            - name: Additional Series
              url: series
            - name: "Contact Me"
              url: /contact-me/

    # home-info mode
    homeInfoParams:
        Title: "Theologicus"
        Content: "Trying to waste my time with God."

    socialIcons:
        - name: twitch
          url: "http://twitch.theologic.us"
        - name: discord
          url: "http://discord.theologic.us"
        - name: youtube
          url: "http://youtube.theologic.us"
        - name: twitter
          url: "https://twitter.com/theologic_us"
        - name: instagram
          url: "https://instagram.com/josephlouthan"
        - name: facebook
          url: "https://www.facebook.com/groups/462231051477464"
        - name: github
          url: "https://github.com/joelouthan"

#    analytics:
#        google:
#            SiteVerificationTag: "G-V3GC3P3REE"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: Series
          name: series
          url: /series/
          weight: 10
        - identifier: Categories
          name: categories
          url: /categories/
          weight: 20
        - identifier: 
          name: tags
          url: /tags/
          weight: 30

taxonomies:
    category: categories
    tag: tags
    series: series

Social:
    facebook: "joseph.louthan"
    instagram: "josephlouthan"
    linkedin: "joelouthan"
    twitter: "josephlouthan"

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

markup:
  goldmark:
    renderer:
      unsafe: true
#       hardWraps: false
#     extensions:
#       definitionList: true
#       footnote: true
#       linkify: true
#       strikethrough: true
#       table: true
#       taskList: true
#       typographer: true
#     parser:
#       attribute: true
#       autoHeadingID: true
#       autoHeadingIDType: github
#     renderer:
#       hardWraps: false
#       unsafe: true
#       xhtml: false
