baseURL: "https://theologic.us"
title: Theologicus
paginate: 1000
theme: PaperMod

rssLimit: 100
copyright: "&copy;2023 by Joseph Louthan &#x2022; All Rights Reserved &#x2022;"
languageCode: "en-us"

author:
    name: "Joseph Louthan"
    email: "joe@theologic.us"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: G-V3GC3P3REE

minify:
    disableXML: true
    minifyOutput: true

params:
    ShowPostNavLinks: true

    env: production
    title: Theologicus
    description: "Trying to waste my time with God. Preacher of the Gospel. Writing at Theologicus. StarCraft 2 Elderly."
    author: Joseph Louthan
    email: joe@theologic.us

    mainSections:
      - "podcasts"
      - "categories"
      - "series"
      - "tags"

    podcast:
      description: "Daily devotions on the goodness of God--based on writings at Theologicus."
      tagline: "Trying to waste my time with God"
      download_url: https://media.theologic.us/audio/
      cdn_url: hhttps://theologic.us/images/
      itunes_url: https://podcasts.apple.com/us/podcast/theologicus/id1680606952
      itunes_id: id1680606952

    defaultTheme: auto # dark, light
    disableThemeToggle: false
    ShowReadingTime: true
    ShowShareButtons: true
    disableSpecial1stPost: false
    comments: false
    hidemeta: false
    showtoc: true
    tocopen: true

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "apple-touch-icon.png"
        safari_pinned_tab: "safari-pinned-tab.svg"

    label:
        text: "Home"
        icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Theologicus
        imageUrl: "images/jlouthan-ai-starry-back-500-01.png"
        imageWidth: 100
        imageHeight: 100
        imageTitle: "Joseph Louthan"
        buttons:
            - name: What Is It?
              url: /about/
            - name: What Is It Not?
              url: /not-about/
            - name: Ministry Resume
              url: /resume/
            - name: Updates
              url: updates
            - name: Recent Posts
              url: posts
            - name: Sermons
              url: /categories/sermons/
            - name: Praying through the Psalms
              url: /series/praying-through-psalms/ 
            - name: "1689"
              url: /tags/1689/
            - name: "The Apostles' Creed"
              url: /series/doctrine-apostles-creed/
            - name: "Devotions: Mark"
              url: /series/devotions-mark/
            - name: "Devotions: Luke"
              url: /series/devotions-luke/
            - name: "Devotions: Matthew"
              url: /series/devotions-matthew/
            - name: "Study: Ruth"
              url: /series/study-ruth/
            - name: "Study: Romans"
              url: /series/study-romans/
            - name: "Study: Genesis"
              url: /series/study-genesis/
            - name: "Gospel: Pastoral Epistles"
              url: /series/gospel-nt-pastorals/
            - name: Additional Series
              url: series
            - name: "Contact Me"
              url: /contact-me/

    # home-info mode
    homeInfoParams:
        Title: "Theologicus"
        Content: "Trying to waste my time with God."

    socialIcons:
        - name: github
          url: "https://github.com/joelouthan"
        - name: mastodon
          url: "https://bibly.com/@joseph"
        - name: linkedin
          url: "https://linkedin.com/in/joelouthan"
        - name: discord
          url: "https://discord.gg/DntJ4rh5eN"
        - name: googlecalendar
          url: "https://calendar.app.google/hMeh4vnexCW29jX46"
        - name: instagram
          url: "https://instagram.com/josephlouthan"
        - name: youtube
          url: "http://youtube.theologic.us"
        - name: applepodcasts
          url: "https://podcasts.apple.com/us/podcast/theologicus/id1680606952"

#    analytics:
#        google:
#            SiteVerificationTag: "G-V3GC3P3REE"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: Series
          name: series
          url: /series/
          weight: 10
        - identifier: Categories
          name: categories
          url: /categories/
          weight: 20
        - identifier: 
          name: tags
          url: /tags/
          weight: 30
        - identifier: 
          name: episodes
          url: /episodes/
          weight: 40

taxonomies:
    category: categories
    tag: tags
    series: series
    podcasts: episodes

Social:
    facebook: "joseph.louthan"
    instagram: "josephlouthan"
    linkedin: "joelouthan"
    github: "joelouthan"

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

outputFormats:
  mp3feed:
    MediaType: "application/rss+xml"
    BaseName: "index"
    path: "/feed/mp3"
    IsHTML: false
    IsPlainText: true
    noUgly: true
    Rel: "alternate"

# Podcast Feed per https://brendamour.net/2021/04/18/how-to-publish-podcasts-with-the-hugo-static-site-generator/

outputs:
  home:
    - HTML
    - AMP
    - RSS
    - mp3feed

markup:
  goldmark:
    renderer:
      unsafe: true
#       hardWraps: false
#     extensions:
#       definitionList: true
#       footnote: true
#       linkify: true
#       strikethrough: true
#       table: true
#       taskList: true
#       typographer: true
#     parser:
#       attribute: true
#       autoHeadingID: true
#       autoHeadingIDType: github
#     renderer:
#       hardWraps: false
#       unsafe: true
#       xhtml: false
