baseURL = "http://theologic.us/"
languageCode = "en-us"
title = "Theologicus"
description = "No pen, no words, no image can express to you the loveliness of my only, only Lord Jesus. - Samuel Rutherford"
theme = "cupper"
