[build]
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.staging.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "staging"
HUGO_ENABLEGITINFO = "true"