---
title: 'Morning Prayers for Thursday, 17 December 2020'
author: Joseph Louthan
type: post
publishDate: 2020-12-17T06:00:00-06:00
url: /prayers/2020-12-17-am_prayers/
categories:
 - Prayers
tags:
 - 'Prayers'
draft: true
---
'''

Lord, do we plant churches in Norman? 

If so, what is mine to do?

What is Sarah's to do?

Amen.

'''
[quote, ]
____

____
[quote, 2 Timothy 4:1-5 (ESV)]
I charge you in the presence of God and of Christ Jesus, who is to judge the living and the dead, and by his appearing and his kingdom: preach the word; be ready in season and out of season; reprove, rebuke, and exhort, with complete patience and teaching. For the time is coming when people will not endure sound teaching, but having itching ears they will accumulate for themselves teachers to suit their own passions, and will turn away from listening to the truth and wander off into myths. As for you, always be sober-minded, endure suffering, do the work of an evangelist, fulfill your ministry.

[quote, Revelation 11:1-14 (ESV)]
____
Then I was given a measuring rod like a staff, and I was told, "`Rise and measure the temple of God and the altar and those who worship there, but do not measure the court outside the temple; leave that out, for it is given over to the nations, and they will trample the holy city for forty-two months. And I will grant authority to my two witnesses, and they will prophesy for 1,260 days, clothed in sackcloth.`"

These are the two olive trees and the two lampstands that stand before the Lord of the earth. And if anyone would harm them, fire pours from their mouth and consumes their foes. If anyone would harm them, this is how he is doomed to be killed. They have the power to shut the sky, that no rain may fall during the days of their prophesying, and they have power over the waters to turn them into blood and to strike the earth with every kind of plague, as often as they desire. And when they have finished their testimony, the beast that rises from the bottomless pit will make war on them and conquer them and kill them, and their dead bodies will lie in the street of the great city that symbolically is called Sodom and Egypt, where their Lord was crucified. For three and a half days some from the peoples and tribes and languages and nations will gaze at their dead bodies and refuse to let them be placed in a tomb, and those who dwell on the earth will rejoice over them and make merry and exchange presents, because these two prophets had been a torment to those who dwell on the earth. But after the three and a half days a breath of life from God entered them, and they stood up on their feet, and great fear fell on those who saw them. Then they heard a loud voice from heaven saying to them, "`Come up here!`" And they went up to heaven in a cloud, and their enemies watched them. And at that hour there was a great earthquake, and a tenth of the city fell. Seven thousand people were killed in the earthquake, and the rest were terrified and gave glory to the God of heaven.

The second woe has passed; behold, the third woe is soon to come.
____

'''

Lord, please bring us a baby.

Lord, how can I be closer to my kids and see them more often?

Please provide a way.

Thank you for providing a decent, good and running truck.

Lord, should we pursue a replacement for the Acura?

I love you, Lord. You alone are my provider.

And Lord, what about this position at work?

Do I take it?

Will it draw me closer to you? Please be with me.

Amen.

'''

== For Sarah

Melissa

Steph

Erin

Faith

Melody

Natasha

Jamie

== Give thanks

You gave me my heart. My provision. My joy.

Whatever I have lost, you have restored a millionfold.

Whatever I have, it comes from your hand and is all your own.

If I have nothing or anything, I have everything because I have your Son, Jesus Christ.

== For healing

My Lord,

I pray for that you would heal:

Heal Kim - help her sleep

cosmicj's wife, Rachel - heal her womb

Sarah Brock - Her friend Verlene who passed away while we we speaking. Please be with the Thurstons: Phil and his kids, Daniel & Camille

Emily - grandma Donna. COVID with mild symptoms

Julie Keller - depression

Jacob Epperson - his son, Wilder, with heart cath surgery in Dallas on 12/4

Deanna & James, Quinn

Keep Melissa. Seal her heart towards you.

Speak to Andrew.

Heal Faithie.

Heal Sean.

Heal Gerry.

Be with Jordan.

Heal Kathleen (Leah's mom)

== Daily

On marriage: *Sarah, my love*

On true friendship: *For my Jonathan*

On sanctification: *Lord, help me to gentle, patient, and tender like you*

On holiness: *2 Timothy 2:21 Therefore, if anyone cleanses himself from what is dishonorable, he will be a vessel for honorable use, set apart as holy, useful to the master of the house, ready for every good work.*

Lord, as you draw me closer, please Lord please stop making everything about me. Please beat it out of me that i somehow think i am God's gift to women. I still see lust on my heart and I still want to look at every woman not my wife.  World is telling me lies. But you have gave me eyes for my wife over anyone else. One day you will remove the foolish, prideful, lustful instincts and thoughts in thinking every woman is after me. I am a fool and a sinner. Every day I will repent. Discipline your son as you see fit but make me more like your Son.  Do not let your Spirit depart from me. Amen.

On prophesying: *Lord, let me preach your gospel, die, and then be forgotten*

On pastoring: *Lord, I cared not where or how I lived, or what hardships I went through, so I could but gain souls to Christ. --Henry Martyn*

On teaching: *"`He who would be a good teacher must be gentle and leave some means to draw those who come to him, that he may win them.`" --John Calvin*

On evangelizing: *As soon as the line snaps: "`In your ministry, you will gain two and lose one. Will that be good enough for you.`"*

On glory of God: *"`On Christ's glory I would fix all my thoughts and desires, and the more I see of the glory of Christ, the more the painted beauties of this world will wither in my eyes and I will be more and more crucified to this world. It will become to me like something dead and putrid, impossible for me to enjoy.`" ― John Owen, The Glory of Christ*

On his provision: *Lord, anything you give will be good enough for me.*

== Next steps

My God,

I am so uncertain. What are my next steps? Direct me, Holy Spirit.

But I will praise you for the triple blessings of being with the staff. Bless them and keep them always.

Amen

== For those who may not know You

My Lord above,

Call on me. I will be obedient. Tell me with whom shall I share your good news: you are Jesus and you have saved his people from their sins. If they believe and trust in you, they will live.

* *Julie Keller*
* *Logan*
* *Chuck's sons, Zachary & Samuel*
* *Aussie's folks: Brad & Gay, 3 brothers*
* *Emily's mom, Cheri*
* *Yusef and Nichole*
* *Elijah & Ivy, Amber & Kara, Griffen, Gabe, Emma, Lacey, Grace, Lucy*
* *Natalie, Jackson, Kingston*
* *Reed & Sandy*
* *Johnny & Jamie, Kolton, Korbin*
* *Jeanny*
* *Jodi & Ryan, Piper, Rylee*
* *Jennifer & John; Brandon; Phillip & Keri, Haley; Meagan & fam ; Pedigo & Deb*
* *Melissa & Micah, Noah, Levi, Judah*
* *James*
* *Jason, Molly*
* *Chelsea*
* *Jansen & Mandy*
* *Sean & Sunny*
* *Evan*
* *Shannon & Michael, Elle*
* *Patrick (Dave's Son)*
* *Coleman & Wendy, Olivia, Bella, Ian*
* *Carl*
* *Mark & Nicole, Gabrielle*
* *Mark & Robin*
* *James & Hubs*
* *Louis*
* *Greg & wife*
* *Liz*
* *Eileen & Hubs, fam*
* *Ray*
* *Randall*
* *Cynthia*
* *Joe P*
* *George*
* *Margo & kids*
* *Vinny & wife*
* *Ali*
* *Homie*
* *Carlos*
* *Kyle*
* *Landon*
* *Jamie*
* *John & wife, kids*
* *Jason Sohn*
* *Dhruv*
* *Yusik*
* *Peter*
* *Wayne & Nicole Barber*
* *Eric Robinson*
* *Jonathan & Jenn Williams*
* *Evan & Kaylee, Everett, Baby*

== StarCraft 2

* Zip
* MrSleep
* ogreinside
* Henex
* Nitrous
* Syrill
* ablindman
* DamGlam
* patch
* batrick
* cosmicj
* Codad
* philosotoss

== D&D

* Andrew & Kara
* Jeff & Emilee
* Hannah

== Friends

* *Sarah & Josiah*
* *Jared & Lacey, Marin, Elisabeth*
* *Leslie*
* *Andrew & Jordyn, Will, Alice, Elliot, Annie*
* *Alix & Braden*
* *Aaron & Natasha, Audrey*
* *Holly & Jake, Jonah, Ellis, Finley*
* *Jason & Michelle, Hazel, Charlotte, Evelyn*
* *Landon & Jules, Eli, Sophia & Olivia*

=== California

* *Moray*
* *Sarah and Mike*
* *Layne and Jackie Marshall*
* *Evie*
* *Kristie*
* *John and Gina*
* *Jen and Diddy*
