---
title: 'Evening Prayers for Sunday, 3 January 2021'
author: Joseph Louthan
type: post
publishDate: 2021-01-03T20:00:00-06:00
url: /pm_prayers/2021-01-03-pm_prayers/
categories:
 - Prayers
tags:
 - 'Prayers'
draft: true
---
'''

Lord, do we plant churches in Norman? 

If so, what is mine to do?

What is Sarah's to do?

Amen.

[quote, ]
____

____
[quote, 2 Timothy 4:1-5 (ESV)]
I charge you in the presence of God and of Christ Jesus, who is to judge the living and the dead, and by his appearing and his kingdom: preach the word; be ready in season and out of season; reprove, rebuke, and exhort, with complete patience and teaching. For the time is coming when people will not endure sound teaching, but having itching ears they will accumulate for themselves teachers to suit their own passions, and will turn away from listening to the truth and wander off into myths. As for you, always be sober-minded, endure suffering, do the work of an evangelist, fulfill your ministry.

[quote, Revelation 11:1-14 (ESV)]
____
Then I was given a measuring rod like a staff, and I was told, "`Rise and measure the temple of God and the altar and those who worship there, but do not measure the court outside the temple; leave that out, for it is given over to the nations, and they will trample the holy city for forty-two months. And I will grant authority to my two witnesses, and they will prophesy for 1,260 days, clothed in sackcloth.`"

These are the two olive trees and the two lampstands that stand before the Lord of the earth. And if anyone would harm them, fire pours from their mouth and consumes their foes. If anyone would harm them, this is how he is doomed to be killed. They have the power to shut the sky, that no rain may fall during the days of their prophesying, and they have power over the waters to turn them into blood and to strike the earth with every kind of plague, as often as they desire. And when they have finished their testimony, the beast that rises from the bottomless pit will make war on them and conquer them and kill them, and their dead bodies will lie in the street of the great city that symbolically is called Sodom and Egypt, where their Lord was crucified. For three and a half days some from the peoples and tribes and languages and nations will gaze at their dead bodies and refuse to let them be placed in a tomb, and those who dwell on the earth will rejoice over them and make merry and exchange presents, because these two prophets had been a torment to those who dwell on the earth. But after the three and a half days a breath of life from God entered them, and they stood up on their feet, and great fear fell on those who saw them. Then they heard a loud voice from heaven saying to them, "`Come up here!`" And they went up to heaven in a cloud, and their enemies watched them. And at that hour there was a great earthquake, and a tenth of the city fell. Seven thousand people were killed in the earthquake, and the rest were terrified and gave glory to the God of heaven.

The second woe has passed; behold, the third woe is soon to come.
____
== The City Church

* Chris & Sawyer Taylor
* Will Bostian
* Karl Visser
* Andrew Rubinson
* Brayden Hudson
* Bailey Voss
* Liz Rech

== Salt+Light Community

* Ben & Jessica, kids
* Matt & Nicole, kids
* Arnett, Byford, Davis, Fort, Howard, Rollings, Shingledecker, Aguilar, Freeman, Kiltz

== Mosaic East

== Antioch Norman

Lord,

Deliver them. Protect them. Keep them.

Shield them from the attacks of the enemy.

You are their Pastor and Lord. Do not let your little ones go astray.

Keep your presence there.

Have you way in them.

== Bethesda Church

* *Pastor Dan & Becky Smith*
* *Mary Evans*
* *Stephen & Alisa Evans, fam*
* *Anthony & wife, fam*

== Gateway Church

* *Kristi*
* *Camille*
* *Court & Lauryn, kids*

== Catch the Fire DFW

* *Alan Smith*
* *Nancy & Sean Love, Lauren, Anna, Teddy*
* *Lenore*
* *Jeremiah Duckett*
* *Erica & Chris, Natalie, Ethan, Suzanna, Emerie*
* *Shannon & Jessica, Eddie*
* *Keri & Greg Solomon, Hazel, Penelope, Rowan*
* *Michael & Erin, Brielle, Malachi, Sebastian*
* *Jon & Lauren Pignatelli,*
* *Kim Marin*
* *Matthew Palant*
* *Brad Braddy*
* *Margie Spence*
* *Tom Gardner*

== Frontline

== Leaders within Frontline

Lord, would you raise up even more leaders for Norman. No matter what direction we take please tap more leaders.  More musicians. More of your Son in each of us so it won't be dependent on any of us but on you alone.

Lord, be glorified in our homes and in our city. Today.

== Core

* *Emily Brown*
* *Aussie Enzbrenner*

== Bois

* *Caleb Dyer*
* *Colson Woodard*
* *William Armer*

== Interns

* Caitlyn Swanson
* Mikayla Sander
* Stephanie White
* Paige Gariepy
* Katie Kalkulak
* AnnaMarie Ross
* Delaney Hammonds
* Savannah Chappell
* Abbigail Thomsen
* Emily Brown
* Jasmine Ingram
* JemiJean Jones
* Julianna Horner
* Mack McCullah
* Curtis Mitchell
* Zach Shomaker
* Aussie Enzbrenner

== Intern Staff

Ariel Mackey

Laker Greenwood

Zach Shomaker

Hope Wilson

Janelle Rogers

== Frontline Norman

Lord,

I believe I have your vision. I do not desire a ministry. My only desire is to faithfully handle your precious word and preach the gospel of Christ and him crucified.

But not my will but your will be done.

Amen.

== Frontline South

=== Please send us another kid's minister - Amen

* *Dena & Dave*
 ** Patrick
 ** Heather & hubs
 ** Ashlyn, Kadence, Liam, Coleman, Brayden, Gray, Madalyn, Hudson
* *Sean & Jacqueline*
* *Andrew & Hilary, Evie, Eleanor, Bear*
* *Aaron & Kara, Beatrix & Peter*
* *Brandon & Rachael, Claire & Jack*
* *Tyler & Heather, Shepherd*
* *Reuben*
* *Tyler & Melanie, Addy, Jocelyn, Kerslyn*
* *Will & Carli, Will, Theo*
* *Dawn & Mark*
 ** Timothy, Elijah & Emily
 ** Tiffany & Nicky, Madilynn, Hunter, Hailey
 ** Daniel
 ** Sara & Rejoe, Emeril, Eredin, Elliot
* *Deanna & James, Quinn*
* *Eric & Megan, Leeland, Baby*

=== Jhigh girls

* Becca Finocchiaro - identity in Jesus apart from siblings, confidence in who Jesus made her.
* Catherine Adams - just lost her step mom in a car wreck, has a lot of brokeness. salvation
* Tatum Coleman - Identity in Jesus and overall growth in Jesus.
* Claire Laib - salvation

=== Jhigh guys

* Ephraim Fox - salvation
* Zachary Ebaucher - salvation
* Noah Morgan - salvation
* Isaac Post - salvation
* Coleman Evans - salvation
* Seth Freeman - attends infrequently, salvation and understanding of who God is to become real.

=== 9th grade guys

* Liam Evans - for God to show himself to be real and tangible.
* Bryson White - salvation.
* JD Morgan - salvation
* Julian Ebaucher - salvation

=== 11th and 12th Guys

* Timothy Finocchiaro - depression and friendships, feels very lonely and aimless.
* Hunter Loughlin - sexual addiction with pornography and struggles to know what the future holds, God to give him a bigger vision of his life and grow him in the Gospel.
* Charlie Longenbough - For Jesus to seem real and attractive to follow in the sake of the worlds offerings. Has an idea of Jesus with no real desire to follow him.

=== HS Girls

* Breeli Stanberry - Depth in the Gospel, is chameleon like and changes depending on who she is around.
* Brooklyn Stanberry - emotional health, struggles with friendships a lot, healing for a past friendship and relationship that fell thru
* Calea Moser - split between two parents, attends once a month
* Mallory Feighner - struggles deeply with what others think, gives her panic attacks, identity in Jesus and growth in emotional health and friendships with other girls
* Emily Finocchiaro - struggles with her loving and respecting mom and brother. really needs help forgiving ways her mom has fallen short and self awareness to see her own sin. praying also for her leadership capabilities to be released through maturing in Jesus
* Sara Freeman - that God would show her life is more than sports. very talented athlete that has a heart for God but parents that prioritize sports. depth in the gospel.
* Ashlyn Evans - for God to heal wounds and heartache from past friendships, give vision and direction for post HS in the next year.
* Zoe Johnson - praying for her to show up more often, is often cliquey and struggles to allow herself to be known, praying God would convict her and give her a spiritual family if she came more.
* Shelby Mathews - emotional health and freedom from anxiety/depression, pressure from parents and sisters to be "`perfect`"
* Hannah Lavender - raised by grandma, attends once a month, really needs healing with rough family and for the Lord to keep her from trying to find identity in hs guys and dating.

== Frontline Midwest City

== Frontline Fayetteville

* John Murphy

== Frontline Shawnee

* Ben Hill
 ** Lord, show me how I can be praying, encouraging and lifting up Ben and all the peoples at Shawnee
* Pat & Kim Robinson
* Matt Emerson
* Jerad Friend
* Rebecca Hilton
* Alex Greenwood
* Hayden Heath
* Ivy Penwell
* Janelle Rogers
* Laker Greenwood
* Aidan Sims
* Jordan Richardson
* Savannah Chappell
* Bill Morgan

== Frontline Yukon

* Chad Puckett
* Blake Burrough
* Jeff Nine
* Leah Swank
* Derek Chapin
* Chad Puckett

== Frontline Edmond

* David Adair
* JJ Seid
* Ryan Gikas
* Eric Platner
* Lyndsey Freeman
* Cale Freeman
* Matt Polk
* Steve Curry
* Rex Barrett

== Frontline Downtown

* Chad Kincer
* John Riner
* Matthew Arbo
* Ernest Odunze
* Brian Elliot
* Kori Hall
* Jake Lenhart
* Dillon Byrd
* Phil Maucieri
* Shelby Duggan
* Garrett Johnson
* Lauren Gilliam
* Dylan Watts
* Josh Morgan
* Zechariah Gullo

== Frontline Central

* Josh Kouri
* Charlie Hall
* Rex Barrett
* Rob Adair
* Aaron Addison
* Jeff Nine
* Kim Robinson
* John Murphy
* Ryan Hunter
* Emilie Polk
* Ariel Mackey
* Joel Miller
* Maddy Morgan
* Janelle Rogers
