name: Trigger Netlify Build
on:
  schedule:
    # Run at 0500 daily UTC
    - cron: '35 12 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_DAILY_BUILD_HOOK }}