name: Trigger Netlify Build

on:
  schedule:
    - cron: '0 10 * * *' #12P = 8A GitHub; Ergo 10A = 5A? I'm Ron Burgundy?

jobs:
  build:
    name: Daily Netlify Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_DAILY_BUILD_HOOK }}