name: Trigger Netlify Build
on:
  schedule:
    # Run at 0500 daily
    - cron: '30 6 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/63b6afdf713ff1191549fad4