name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  build:
    name: Daily Netlify Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_DAILY_BUILD_HOOK }}